name: Deployment - Production

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Setup the environment
      - name: Environment setup
        id: env
        run: |
          echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"

      # Build the application
      - uses: actions/checkout@v2
      - name: Docker image build
        run: |
          docker build -t "${{ steps.env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .

      # Login to the package repository
      - name: Package repository login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      # Publish the image to the package repository
      - name: Docker image publish 
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/${{ steps.env.outputs.IMAGE_NAME }}"

      # Deploy the application on the virtual machine
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_DO_HOST }}
          username: ${{ secrets.PRODUCTION_DO_USERNAME }}
          password: ${{ secrets.PRODUCTION_DO_PASSWORD }}
          port: ${{ secrets.PRODUCTION_DO_PORT }}
          script: |
            cd ~/deployment/production
            ./${{ steps.env.outputs.IMAGE_NAME }}.sh
